name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "./requirements.txt"

      - name: PyTest
        run: pytest --junit-xml pytest.xml

      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: pytest.xml

  publish-test-results:
    name: Publish Unit Test Results
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml